import { existsSync, mkdtempSync, readFileSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { formatFile, parserForFile } from '../src/utils/formatFile';
import { writeFileSafely } from '../src/utils/writeFileSafely';

/**
 * `formatFile` used to hard-code `parser: 'typescript'` for every write, so any
 * non-TypeScript artefact threw inside `writeFileSafely` and was swallowed by
 * its catch: the file never reached disk, yet generation reported success and
 * exited 0.
 *
 * The Pro packs are where this bit hardest — `openapi.json`, `openapi.yaml`,
 * `index.html`, `policies.sql`, `README.md` and `api_client.py` all vanished
 * unless the output path happened to contain the literal substring
 * `/generated/pro/`, which is the only branch that skipped formatting.
 */
describe('non-TypeScript artefacts reach disk', () => {
  let dir: string;

  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), 'pzg-artifacts-'));
  });

  afterAll(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('picks a parser from the file extension', () => {
    expect(parserForFile('a/b/openapi.json')).toBe('json');
    expect(parserForFile('a/b/README.md')).toBe('markdown');
    expect(parserForFile('a/b/openapi.yaml')).toBe('yaml');
    expect(parserForFile('a/b/index.html')).toBe('html');
    expect(parserForFile('a/b/schema.ts')).toBe('typescript');
    expect(parserForFile('a/b/mock-server.js')).toBe('babel');
    // Prettier has no parser for these: they must pass through untouched.
    expect(parserForFile('a/b/policies.sql')).toBeUndefined();
    expect(parserForFile('a/b/api_client.py')).toBeUndefined();
    expect(parserForFile('a/b/LICENSE')).toBeUndefined();
  });

  it('returns unparseable content unchanged instead of throwing', async () => {
    const sql = 'ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;\n';
    await expect(formatFile(sql, 'policies.sql')).resolves.toBe(sql);
  });

  it('still parses as TypeScript when no file path is given', async () => {
    // Preserves the original contract for the core schema writers.
    await expect(formatFile('const a  =  1', undefined)).resolves.toContain('const a = 1;');
  });

  it.each([
    ['policies.sql', 'CREATE POLICY "tenant_isolation" ON "User" USING (true);\n'],
    ['api_client.py', 'class ApiClient:\n    pass\n'],
    ['openapi.json', '{"openapi":"3.0.3","paths":{}}'],
    ['README.md', '# Row Level Security\n\nGenerated by PZG Pro.\n'],
    ['openapi.yaml', 'openapi: 3.0.3\npaths: {}\n'],
  ])('writes %s to a path with no /generated/pro/ segment', async (name, content) => {
    const target = join(dir, 'pro-output', name);

    await writeFileSafely(target, content, false);

    expect(existsSync(target), `${name} was not written`).toBe(true);
    expect(readFileSync(target, 'utf-8').length).toBeGreaterThan(0);
  });

  it('keeps JSON artefacts valid and complete', async () => {
    const target = join(dir, 'json-check', 'openapi.json');
    const spec = { openapi: '3.0.3', info: { title: 'API', version: '1.0.0' }, paths: {} };

    await writeFileSafely(target, JSON.stringify(spec), false);

    expect(JSON.parse(readFileSync(target, 'utf-8'))).toEqual(spec);
  });

  it('writes a file even when its content cannot be formatted', async () => {
    // Malformed TypeScript: previously the parse error meant no file at all.
    const target = join(dir, 'broken', 'broken.ts');
    const content = 'export const = ;;; not valid typescript';

    await writeFileSafely(target, content, false);

    expect(existsSync(target)).toBe(true);
    expect(readFileSync(target, 'utf-8')).toBe(content);
  });
});
