import fs from 'fs';
import path from 'path';
import {
  sameTypedJsonResolution,
  type ResolvedTypedJsonConfig,
  type TypedJsonTypeResolution,
} from '../config/typed-json';
import Transformer from '../transformer';

/**
 * The `declare global` emitter for `typedJson.emitNamespace`.
 *
 * What it is for: prisma-json-types-generator reads `namespace PrismaJson` and types the
 * Prisma Client from it, which means the shape is authored twice, once as a TypeScript
 * type and once as a Zod schema. Emitting the namespace from the schemas removes the
 * second copy: the Zod schema is authored, the type is `z.infer` of it, and they cannot
 * drift.
 *
 * What it is not: this does not type the Prisma Client. PJTG works by rewriting the
 * client's `index.d.ts`; a `declare global` block alone does nothing to it. PJTG stays in
 * the toolchain for that, and after this there is still exactly one authored definition.
 *
 * A namespace that does not compile is worse than none, so anything this module cannot
 * derive confidently is skipped with a warning rather than guessed at. Skipping costs the
 * user one `PrismaJson.X` they have to write themselves; guessing costs them a type that
 * silently disagrees with the schema validating the same data.
 *
 * This module writes one standalone declaration file and touches no other emitted output.
 */

/**
 * First line of every file this module writes, and the marker that lets a rerun tell its
 * own output apart from a file the user wrote.
 */
export const GENERATED_BANNER = 'Generated by prisma-zod-generator. Do not edit.';

/** One annotated field's contribution to the namespace. */
export interface TypedJsonNamespaceBinding {
  /** The `[TypeName]` written in the annotation. */
  typeName: string;
  /** Model the annotation was found on, for traceability and clash reporting. */
  model: string;
  /** Field the annotation was found on. */
  field: string;
  /**
   * How that type name resolved, from `resolveTypedJsonType`.
   *
   * Passed in rather than recomputed here: the reader has already decided what schema it
   * used for the field, and the namespace must declare *that*, not a second opinion.
   */
  resolution: TypedJsonTypeResolution;
}

export interface BuildTypedJsonNamespaceInput {
  bindings: TypedJsonNamespaceBinding[];
  config: ResolvedTypedJsonConfig;
  /**
   * Directory that a relative `schemaModule` and a relative `namespaceOutput` are
   * resolved against, normally the generator output directory.
   */
  baseDir: string;
  /** Module `z` is imported from. Defaults to `zod`; follows `zodImportTarget`. */
  zodImportSpecifier?: string;
  /**
   * Extension appended to a relative import specifier, for example `.js`.
   *
   * Defaults to whatever the `prisma-client` generator block implies, which is what every
   * other file this generator writes uses. It has to be the same answer: under
   * `moduleResolution: nodenext` a relative ESM import without an extension is
   * `error TS2835`, so one file disagreeing with the rest stops the whole emitted tree
   * compiling. Empty for everyone not on NodeNext, which is the unchanged default.
   */
  importExtension?: string;
}

/** A type name annotated twice, resolving to two different schemas. */
export interface TypedJsonNamespaceConflict {
  typeName: string;
  /** The binding that was declared. */
  used: TypedJsonNamespaceBinding;
  /** Bindings ignored because they disagreed with it. */
  ignored: TypedJsonNamespaceBinding[];
}

export interface TypedJsonNamespaceResult {
  /** The file's contents, or `null` when there is nothing to declare. */
  content: string | null;
  /** Absolute path the file would be written to. */
  filePath: string;
  /** Type names declared, in emitted order. */
  declared: string[];
  /** Type names left out, with the reason. */
  skipped: Array<{ typeName: string; reason: string }>;
  conflicts: TypedJsonNamespaceConflict[];
  warnings: string[];
}

/** Where the namespace file goes for a given output directory. */
export function typedJsonNamespacePath(config: ResolvedTypedJsonConfig, baseDir: string): string {
  return path.isAbsolute(config.namespaceOutput)
    ? config.namespaceOutput
    : path.resolve(baseDir, config.namespaceOutput);
}

/**
 * Rewrite a module specifier so it resolves from `fromDir`.
 *
 * A relative `schemaModule` is written once, in the config, relative to the output
 * directory; the file importing it can sit anywhere under that directory. Package
 * specifiers are used verbatim, since they do not depend on the importer's location.
 *
 * `extension` is appended to a relative specifier that does not already carry one, by the
 * same rule `resolveImportSpecifier` applies to every other emitted import - the two have
 * to agree, or the namespace file is the one file in the tree NodeNext rejects.
 */
function specifierFrom(
  specifier: string,
  baseDir: string,
  fromDir: string,
  extension: string,
): string {
  if (!specifier.startsWith('.')) {
    return specifier;
  }
  const target = path.resolve(baseDir, specifier);
  let relative = path.relative(fromDir, target).split(path.sep).join('/');
  if (relative.length === 0) {
    relative = '.';
  }
  const rewritten = relative.startsWith('.') ? relative : `./${relative}`;
  // `includes('.', 1)` rather than `extname`: it ignores a leading dot, so `./.config`
  // still counts as extensionless.
  if (extension !== '' && !path.posix.basename(rewritten).includes('.', 1)) {
    return `${rewritten}${extension}`;
  }
  return rewritten;
}

function originOf(binding: TypedJsonNamespaceBinding): string {
  return `${binding.model}.${binding.field}`;
}

/**
 * Plain code-unit order, not `localeCompare`: which binding wins a clash, and therefore
 * the bytes of the emitted file, must not depend on the machine's locale.
 */
function compareBindings(a: TypedJsonNamespaceBinding, b: TypedJsonNamespaceBinding): number {
  const left = originOf(a);
  const right = originOf(b);
  return left < right ? -1 : left > right ? 1 : 0;
}

/**
 * Build the `declare global` file.
 *
 * Returns `content: null` when nothing survives - no annotated fields at all, or none
 * whose type could be derived. Callers must write no file in that case: an empty
 * declaration file is a file the user has to explain to themselves later.
 */
export function buildTypedJsonNamespace(
  input: BuildTypedJsonNamespaceInput,
): TypedJsonNamespaceResult {
  const { bindings, config, baseDir } = input;
  const zodSpecifier = input.zodImportSpecifier ?? 'zod';
  // Read from the same place every other emitter reads it, so a caller that says nothing
  // still gets the specifier the rest of the tree uses rather than a bare one.
  const importExtension = input.importExtension ?? Transformer.getImportFileExtension();
  const filePath = typedJsonNamespacePath(config, baseDir);
  const fromDir = path.dirname(filePath);

  const skipped: Array<{ typeName: string; reason: string }> = [];
  const conflicts: TypedJsonNamespaceConflict[] = [];
  const warnings: string[] = [];

  // Group by type name. Two models annotating `[Config]` is normal and means one
  // declaration; two models annotating it with different schemas is a real problem,
  // because the namespace has exactly one slot for the name.
  const byTypeName = new Map<string, TypedJsonNamespaceBinding[]>();
  for (const binding of [...bindings].sort(compareBindings)) {
    const existing = byTypeName.get(binding.typeName);
    if (existing) existing.push(binding);
    else byTypeName.set(binding.typeName, [binding]);
  }

  interface Declaration {
    typeName: string;
    importName: string;
    module: string;
    origins: string[];
    conflict?: TypedJsonNamespaceConflict;
  }

  const declarations: Declaration[] = [];

  for (const typeName of [...byTypeName.keys()].sort()) {
    const group = byTypeName.get(typeName)!;
    const [primary, ...rest] = group;

    const disagreeing = rest.filter(
      (other) => !sameTypedJsonResolution(primary.resolution, other.resolution),
    );
    let conflict: TypedJsonNamespaceConflict | undefined;
    if (disagreeing.length > 0) {
      conflict = { typeName, used: primary, ignored: disagreeing };
      conflicts.push(conflict);
      warnings.push(
        `[typedJson] "${typeName}" is annotated on ${[primary, ...disagreeing]
          .map(originOf)
          .join(' and ')} but resolves to different schemas ` +
          `(${describeResolution(primary.resolution)} vs ${disagreeing
            .map((b) => describeResolution(b.resolution))
            .join(', ')}). ` +
          `The ${config.namespace} namespace has one slot per name, so it was declared from ` +
          `${originOf(primary)}. Give the annotations distinct type names, or point them at the same schema.`,
      );
    }

    if (primary.resolution.kind === 'unresolved') {
      const reason = primary.resolution.reason;
      skipped.push({ typeName, reason });
      warnings.push(
        `[typedJson] Left "${typeName}" out of the ${config.namespace} namespace: ${reason} ` +
          `(annotated on ${group.map(originOf).join(', ')}).`,
      );
      continue;
    }

    if (primary.resolution.kind === 'mapped') {
      const reason =
        'typedJson.map resolves it to an inline expression, which has no importable ' +
        'binding to derive a type from';
      skipped.push({ typeName, reason });
      warnings.push(
        `[typedJson] Left "${typeName}" out of the ${config.namespace} namespace: ${reason} ` +
          `(annotated on ${group.map(originOf).join(', ')}). Move the schema into ` +
          `typedJson.schemaModule if you want the type derived.`,
      );
      continue;
    }

    declarations.push({
      typeName,
      importName: primary.resolution.importName,
      module: primary.resolution.module,
      // Only the origins that agree; a disagreeing one is not described by this type.
      origins: group
        .filter((b) => !disagreeing.includes(b))
        .map(originOf)
        .sort(),
      conflict,
    });
  }

  if (declarations.length === 0) {
    return { content: null, filePath, declared: [], skipped, conflicts, warnings };
  }

  // One import statement per module, names sorted, and only names actually referenced -
  // an unused import is a compile error under noUnusedLocals.
  const imports = new Map<string, Set<string>>();
  for (const declaration of declarations) {
    const specifier = specifierFrom(declaration.module, baseDir, fromDir, importExtension);
    const names = imports.get(specifier) ?? new Set<string>();
    names.add(declaration.importName);
    imports.set(specifier, names);
  }

  const lines: string[] = [];
  lines.push(`// ${GENERATED_BANNER}`);
  lines.push('//');
  lines.push(
    `// Derives the ${config.namespace} namespace from the Zod schemas that validate these`,
  );
  lines.push('// fields, so the schema is the single authored definition and the TypeScript type');
  lines.push('// cannot drift from it.');
  lines.push('//');
  lines.push(
    '// This does not type the Prisma Client on its own: prisma-json-types-generator rewrites',
  );
  lines.push('// the client, and a declare global block alone does not.');
  lines.push('');
  lines.push(`import type { z } from '${zodSpecifier}';`);
  for (const specifier of [...imports.keys()].sort()) {
    const names = [...imports.get(specifier)!].sort();
    lines.push(`import type { ${names.join(', ')} } from '${specifier}';`);
  }
  lines.push('');
  lines.push('declare global {');
  lines.push(`  namespace ${config.namespace} {`);

  declarations.forEach((declaration, index) => {
    if (index > 0) lines.push('');
    if (declaration.conflict) {
      lines.push('    /**');
      lines.push(`     * ${declaration.origins.join(', ')}`);
      lines.push('     *');
      lines.push(
        `     * Also annotated on ${declaration.conflict.ignored
          .map(originOf)
          .join(', ')}, which resolves to a different schema. Declared once, from ` +
          `${originOf(declaration.conflict.used)}.`,
      );
      lines.push('     */');
    } else {
      lines.push(`    /** ${declaration.origins.join(', ')} */`);
    }
    lines.push(`    type ${declaration.typeName} = z.infer<typeof ${declaration.importName}>;`);
  });

  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('export {};');
  lines.push('');

  return {
    content: lines.join('\n'),
    filePath,
    declared: declarations.map((d) => d.typeName),
    skipped,
    conflicts,
    warnings,
  };
}

function describeResolution(resolution: TypedJsonTypeResolution): string {
  switch (resolution.kind) {
    case 'module':
      return `${resolution.importName} from '${resolution.module}'`;
    case 'mapped':
      return `the typedJson.map expression ${resolution.expression}`;
    default:
      return 'nothing';
  }
}

export interface WriteTypedJsonNamespaceResult {
  /** Where the file was written, or `null` when nothing was written. */
  filePath: string | null;
  /** Set when an existing file blocked the write, so "nothing to write" stays distinct. */
  refusedPath: string | null;
  declared: string[];
  skipped: Array<{ typeName: string; reason: string }>;
  conflicts: TypedJsonNamespaceConflict[];
  warnings: string[];
}

/**
 * Write the namespace file, creating whatever directories `namespaceOutput` needs.
 *
 * Writes nothing when `emitNamespace` is off or there is nothing to declare, and returns
 * `filePath: null` so the caller can tell the difference between "wrote it" and "there
 * was nothing to write".
 *
 * `namespaceOutput` is the one path here that is meant to point *outside* the output
 * directory, because the declaration is only useful where the consumer's tsconfig already
 * looks - normally `src/`. Nothing else in the pipeline guards that path, and the safe
 * cleanup machinery does not cover it, so a file this module did not write is left alone
 * and reported instead of overwritten. Refusing costs a warning; the alternative costs
 * someone their file.
 */
export async function writeTypedJsonNamespace(
  input: BuildTypedJsonNamespaceInput,
): Promise<WriteTypedJsonNamespaceResult> {
  const result = buildTypedJsonNamespace(input);

  if (!input.config.emitNamespace || result.content === null) {
    return {
      filePath: null,
      refusedPath: null,
      declared: result.declared,
      skipped: result.skipped,
      conflicts: result.conflicts,
      warnings: input.config.emitNamespace ? result.warnings : [],
    };
  }

  if (fs.existsSync(result.filePath)) {
    let existing = '';
    try {
      existing = fs.readFileSync(result.filePath, 'utf-8');
    } catch {
      existing = '';
    }
    if (!existing.includes(GENERATED_BANNER)) {
      return {
        filePath: null,
        refusedPath: result.filePath,
        declared: result.declared,
        skipped: result.skipped,
        conflicts: result.conflicts,
        warnings: [
          ...result.warnings,
          `[typedJson] Not writing the ${input.config.namespace} namespace to ${result.filePath}: ` +
            `a file is already there and it was not generated by prisma-zod-generator. ` +
            `Point typedJson.namespaceOutput somewhere else, or delete that file if it is stale.`,
        ],
      };
    }
  }

  fs.mkdirSync(path.dirname(result.filePath), { recursive: true });
  fs.writeFileSync(result.filePath, result.content, 'utf-8');

  return {
    filePath: result.filePath,
    refusedPath: null,
    declared: result.declared,
    skipped: result.skipped,
    conflicts: result.conflicts,
    warnings: result.warnings,
  };
}
