name: Bug report
description: Report a problem to help improve Prisma Zod Generator
labels: ['kind/bug']
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thanks for taking the time to report an issue.

        🚨 Sponsor to keep this project active (faster fixes and responses): [GitHub Sponsors →](https://github.com/sponsors/omar-dulaimi)

  - type: checkboxes
    id: preflight
    attributes:
      label: Before you start
      options:
        - label: I searched existing issues and discussions for duplicates
          required: true
        - label: I’m using the latest version of prisma-zod-generator
          required: true
        - label: I have starred the repository to support the project ⭐
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior
      value: |
        <!--
        1. Go to '...'
        2. Change '...'
        3. Run '...'
        4. See error
        -->
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?

  - type: textarea
    id: prisma
    attributes:
      label: Prisma schema / query snippet
      description: Your Prisma schema or relevant query code (do not include secrets)
      value: |
        <!-- Do not include database credentials when sharing your Prisma schema! -->
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Where does this problem occur?
      value: |
        - OS: <!-- e.g. macOS, Windows, Ubuntu -->
        - Database: <!-- PostgreSQL, MySQL, MongoDB, SQLite, SQL Server -->
        - Node.js: <!-- node -v -->
        - Prisma: <!-- prisma -v (paste in next field too) -->
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Prisma and related versions
      description: Output of `npx prisma -v` (and relevant package versions)
      value: |
        ```
        # prisma -v

        ```
    validations:
      required: true
